const primaryRoutes = [
  '/',
  '/about',
  '/contact',
  '/projects',
  '/projects/the-bit-blog',
  '/projects/bit-dev',
  '/projects/cohen-codes',
  '/blog/building-scalable-react-native-apps-with-independent-bit-components-lixj8lgq',
  '/blog/author/nitsan-cohen',
  '/blog/how-to-create-reusable-css-components-with-bit-lhdn5jpc',
  '/blog/how-to-update-dependencies-in-a-scope-lgv69z5c',
  '/blog/bit-components-build-time-and-runtime-consumption-lgmaprww',
  '/blog/setting-the-right-context-for-your-component-previews-lflejin4',
  '/blog/deploying-a-composable-react-app-to-netlify-l7rlluzs',
  '/blog/composable-link-component-that-works-in-any-react-meta-framework-l7i3qgmw',
  '/blog/theming-react-apps-with-styled-components-and-bit-l7epurug',
  '/blog/how-to-create-a-composable-react-app-with-bit-l7ejpfhc',
  '/blog/sharing-types-between-your-frontend-and-backend-applications-l5qih48g',
  '/blog/sharing-javascript-utility-functions-across-projects-l557lr9k',
  '/blog/how-to-reuse-react-components-across-your-projects-l4pz83f4',
  '/blog/composing-reusable-landing-pages-in-components-l4mk36jk',
  '/blog/how-to-build-a-reusable-cloudflare-worker-component-l4bf0swo',
  '/blog/how-to-build-material-ui-components-with-bit-l3isiibs',
  '/blog/component-spotlight-composable-search-bar--l2ndd0k8',
  '/blog/design-tokens-in-components-with-react-and-bit-l28qlxq6',
  '/blog/-extracting-and-reusing-pre-existing-components-using-bit-add-l28qlxpz',
  '/blog/extendable-uis-how-to-build-better-uis-for-developers-l1jkl1pc',
];

module.exports.prerenderRoutes = [...primaryRoutes];
